baseURL = 'https://curlyfr.io/'
languageCode = 'en-us'
title = 'curlyfr.io'
theme        = "hello-friend-ng"
paginate     = 10

[params]
  daterm        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Software engineer with a focus on distributed systems, security, and reverse engineering. Also an amateur musician and artist."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "personal site"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "curlyfry"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "A simple theme for Hugo"

    [languages.en.params.logo]
      logoText = "flippin bits and eatin grits"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  [[menu.main]]
    identifier = "art"
    name       = "art"
    url        = "/pages/art"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/pages/about"